**Theory Questions: **

1. What are data structures, and why are they important?
->Data structures are ways of organizing and storing data to enable efficient access and modification. They are important because they help in writing optimized code, improving performance, and solving complex problems effectively.

2. Explain the difference between mutable and immutable data types with examples?
-> Mutable data types can be changed after creation, like lists ([1, 2, 3] can become [1, 2, 4]). Immutable data types cannot be changed after creation, like tuples ((1, 2, 3)) or strings ("hello")

3.  What are the main differences between lists and tuples in Python?
-> The main differences between lists and tuples in Python are:
Mutability: Lists are mutable (can be changed), while tuples are immutable (cannot be changed).
Syntax: Lists use square brackets [ ], tuples use parentheses ( ).
Performance: Tuples are generally faster and use less memory than lists.

4.  Describe how dictionaries store data?
-> Dictionaries in Python store data as key-value pairs. Each key is unique and maps to a value, allowing fast access to data using the key. Internally, dictionaries use a hash table to quickly find values.

5. Why might you use a set instead of a list in Python?
-> We might use a set instead of a list when you need to store unique elements and perform fast membership tests. Sets automatically remove duplicates and offer faster lookup compared to lists.

6. What is a string in Python, and how is it different from a list?
-> A string in Python is a sequence of characters enclosed in quotes, like "hello". Unlike lists, strings are immutable (cannot be changed) and specifically hold text, while lists can hold any data type and are mutable.

7.  How do tuples ensure data integrity in Python?
-> Tuples ensure data integrity in Python by being immutable, meaning their values cannot be changed after creation. This makes them ideal for storing fixed, constant data and helps prevent accidental modifications.

8. What is a hash table, and how does it relate to dictionaries in Python?
-> A hash table is a data structure that maps keys to values using a hash function to compute an index. In Python, dictionaries use hash tables internally to store key-value pairs, allowing for fast access, insertion, and deletion

9.  Can lists contain different data types in Python?
-> Yes, lists in Python can contain different data types, such as integers, strings, floats, or even other lists. Example: [1, "hello", 3.14, [2, 4]].

10. Explain why strings are immutable in Python?
-> Strings are immutable in Python to ensure data integrity, security, and performance. This allows strings to be safely shared, cached, and used as dictionary keys without risk of accidental changes.

11. What advantages do dictionaries offer over lists for certain tasks ?
-> Dictionaries offer faster data lookup using keys and allow key-value pair storage, making them ideal for tasks like counting items, storing configurations, or mapping relationships. Unlike lists, they provide constant-time access to elements by key.

12. Describe a scenario where using a tuple would be preferable over a list?
-> Using a tuple is preferable when you need to store a fixed set of values that shouldn’t change, like coordinates (x, y) or dates. Tuples are also more memory-efficient and can be used as keys in dictionaries.

13. How do sets handle duplicate values in Python?
-> Sets in Python automatically remove duplicate values. When you add duplicates to a set, only one instance is kept, ensuring all elements are unique.

14. How does the “in” keyword work differently for lists and dictionaries?
-> In lists, the in keyword checks if a value exists in the list. In dictionaries, it checks if a key exists, not the value.
Example:
5 in [1, 2, 5] → True
"name" in {"name": "Sahithi"} → True

15. Can you modify the elements of a tuple? Explain why or why not?
-> No, you cannot modify the elements of a tuple because tuples are immutable. Once created, their content cannot be changed, which helps ensure data stays constant and safe from accidental updates.

16. What is a nested dictionary, and give an example of its use case?
-> A nested dictionary is a dictionary within another dictionary, used to represent complex, structured data.

Example use case: Storing student records:
students = {
    "101": {"name": "Alice", "grade": "A"},
    "102": {"name": "Bob", "grade": "B"}
}

17. Describe the time complexity of accessing elements in a dictionary?
-> Accessing elements in a dictionary has an average-case time complexity of O(1) due to its use of a hash table. This allows for fast lookups by key, regardless of the dictionary size.

18. In what situations are lists preferred over dictionaries?
-> Lists are preferred over dictionaries when you need to store ordered sequences of items, especially when position matters or when duplicate values are needed. They are ideal for tasks like iterating, sorting, or storing simple collections.

19. Why are dictionaries considered unordered, and how does that affect data retrieval?
-> Dictionaries were considered unordered before Python 3.7, meaning the insertion order wasn't preserved. Since Python 3.7, they maintain insertion order, but they’re still designed for key-based access, not position. This affects data retrieval by focusing on keys, not order.

20. Explain the difference between a list and a dictionary in terms of data retrieval?
-> In a list, data is retrieved using index positions (e.g., my_list[0]), while in a dictionary, data is retrieved using keys (e.g., my_dict["name"]). Lists are ideal for ordered data, dictionaries for labeled data.

**Practical Questions**

1.  Write a code to create a string with your name and print it?

In [ ]:
name = "Sahithi"
print(name)

Sahithi

2.  Write a code to find the length of the string "Hello World"

In [ ]:
text = "Hello World"
print(len(text))

11

3.  Write a code to slice the first 3 characters from the string "Python Programming"

In [ ]:
text = "Python Programming"
print(text[:3])

Pyt

4.  Write a code to convert the string "hello" to uppercase

In [ ]:
text = "hello"
print(text.upper())

HELLO

5. Write a code to replace the word "apple" with "orange" in the string "I like apple"

In [ ]:
text = "I like apple"
new_text = text.replace("apple", "orange")
print(new_text)

I like orange

6. Write a code to create a list with numbers 1 to 5 and print it

In [ ]:
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]

7. Write a code to append the number 10 to the list [1, 2, 3, 4]P

In [ ]:
numbers = [1, 2, 3, 4]
numbers.append(10)
print(numbers)

[1, 2, 3, 4, 10]

8.  Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

In [ ]:
numbers = [1, 2, 3, 4, 5]
numbers.remove(3)
print(numbers)

[1, 2, 4, 5]

9.  Write a code to access the second element in the list ['a', 'b', 'c', 'd']

In [ ]:
letters = ['a', 'b', 'c', 'd']
print(letters[1])

b

 10. Write a code to reverse the list [10, 20, 30, 40, 50].

In [ ]:
numbers = [10, 20, 30, 40, 50]
numbers.reverse()
print(numbers)

[50, 40, 30, 20, 10]

In [ ]:
11.

11. Write a code to create a tuple with the elements 100, 200, 300 and print it.

In [ ]:
my_tuple = (100, 200, 300)
print(my_tuple)

(100, 200, 300)

12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

In [1]:
colors = ('red', 'green', 'blue', 'yellow')
second_to_last = colors[-2]
print("Second-to-last element:", second_to_last)

Second-to-last element: blue

12. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [2]:
numbers = (10, 20, 5, 15)
minimum = min(numbers)
print("Minimum number:", minimum)

Minimum number: 5

14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [3]:
animals = ('dog', 'cat', 'rabbit')
index_of_cat = animals.index('cat')
print("Index of 'cat':", index_of_cat)

Index of 'cat': 1

15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [5]:
fruits = ('apple', 'banana', 'orange')

# Check if "kiwi" is in the tuple
if 'kiwi' in fruits:
    print("Yes, 'kiwi' is in the tuple.")
else:
    print("No, 'kiwi' is not in the tuple.")

No, 'kiwi' is not in the tuple.

16. . Write a code to create a set with the elements 'a', 'b', 'c' and print it.

In [6]:
my_set = {'a', 'b', 'c'}
print("Set contents:", my_set)

Set contents: {'a', 'b', 'c'}

17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

In [7]:
my_set = {1, 2, 3, 4, 5}
my_set.clear()
print("Set after clearing:", my_set)

Set after clearing: set()

18.  Write a code to remove the element 4 from the set {1, 2, 3, 4}.

In [8]:
my_set = {1, 2, 3, 4}
my_set.remove(4)
print("Set after removing 4:", my_set)

Set after removing 4: {1, 2, 3}

19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

In [1]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

union_set = set1.union(set2)
print("Union of the sets:", union_set)

Union of the sets: {1, 2, 3, 4, 5}

20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

In [2]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}

intersection_set = set1.intersection(set2)
print("Intersection of the sets:", intersection_set)

Intersection of the sets: {2, 3}

21.  Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

In [3]:
person = {
    "name": "Sahithi",
    "age": 30,
    "city": "hyderabad"
}

print("Dictionary:", person)

Dictionary: {'name': 'Sahithi', 'age': 30, 'city': 'hyderabad'}

22.  Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}

In [4]:
person = {'name': 'John', 'age': 25}
person['country'] = 'USA'

print("Updated dictionary:", person)

Updated dictionary: {'name': 'John', 'age': 25, 'country': 'USA'}

23.  Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [5]:
person = {'name': 'Alice', 'age': 30}
name_value = person['name']

print("Value associated with 'name':", name_value)

Value associated with 'name': Alice

24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}

In [6]:
person = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del person['age']

print("Updated dictionary:", person)

Updated dictionary: {'name': 'Bob', 'city': 'New York'}

25.  Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}

In [7]:
person = {'name': 'Alice', 'city': 'Paris'}

if 'city' in person:
    print("The key 'city' exists in the dictionary.")
else:
    print("The key 'city' does not exist in the dictionary.")

The key 'city' exists in the dictionary.

26. Write a code to create a list, a tuple, and a dictionary, and print them all.

In [8]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a tuple
my_tuple = ('apple', 'banana', 'cherry')

# Creating a dictionary
my_dict = {'name': 'Emma', 'age': 28, 'city': 'London'}

# Printing them
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3, 4, 5]
Tuple: ('apple', 'banana', 'cherry')
Dictionary: {'name': 'Emma', 'age': 28, 'city': 'London'}

27.  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)

In [9]:
import random

# Create a list of 5 random numbers between 1 and 100
random_numbers = random.sample(range(1, 101), 5)

# Sort the list in ascending order
random_numbers.sort()

# Print the result
print("Sorted list of random numbers:", random_numbers)

Sorted list of random numbers: [6, 25, 30, 37, 46]

28.  Write a code to create a list with strings and print the element at the third index.

In [10]:
# Creating a list with strings
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']

# Accessing and printing the element at the third index
print("Element at index 3:", my_list[3])

Element at index 3: date

29.  Write a code to combine two dictionaries into one and print the result.

In [11]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

# Combine the dictionaries
combined_dict = {**dict1, **dict2}

# Print the result
print("Combined dictionary:", combined_dict)

Combined dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

30.  Write a code to convert a list of strings into a set.

In [12]:
# List of strings
my_list = ['apple', 'banana', 'cherry', 'apple', 'banana']

# Convert list to set
my_set = set(my_list)

# Print the result
print("Set:", my_set)

Set: {'apple', 'cherry', 'banana'}